server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/appdb
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
